### ISSUE TITLE
swap to ggrs built-in desync detection

### ISSUE THREAD

**Issue by cscorley** [cscorley/bevy_ggrs_rapier_example#26]
After the Bevy 0.10 update, we can swap this example to use the new built-in desync detection in GGRS.

Pros:
- Easy to implement
- Easy to understand (just turn it on!)
- Lots of systems and stuff get dropped here

Cons:
- Only hashes the declared components and resources with reflect, and does not hash pure physics state

However, I think this con is completely mitigated because we already have to save off the physics state into a dedicated resource anyhow, and *that* is Reflect(Hash) since it is just one big Vec<u8>.  This uses bevy's ahash, which is deterministic on the same platform, but not sure about cross platform yet.  Would still need to figure out if that is true or not.

**Comment by cscorley** [comment]
as an alternative, matchbox also now has a nice side socket for other messages that could be useful to send over the hashes instead of globbing them onto the input

**Comment by cscorley** [comment]
I think it is plausible for this to not have the same hash cross platform yet due to ahash.  I have not been able to test to confirm this, but I think this will be the case just going by documentation and reading the bevy source around this.  I think we'd have to patch bevy to have an even more deterministic hasher for it's reflect_hash

**Comment by cscorley** [comment]
I tried to implement this.  I think there are serious issues with the GGRS desync detection that require specific implementation workarounds.  It sends unconfirmed frames and uses them to validate.  I think it needs to be re-written with the concepts we have here.

**Comment by solnyszczko** [comment]
> I tried to implement this. I think there are serious issues with the GGRS desync detection that require specific implementation workarounds. It sends unconfirmed frames and uses them to validate. I think it needs to be re-written with the concepts we have here.

proof?

**Comment by cscorley** [comment]
It is obvious.  Just simply using it because it detects desyncs before rollbacks occur.  The proof is in the plugin source code, which you are welcome to read also.

**Comment by cscorley** [comment]
Good news, this was fixed in https://github.com/gschup/ggrs/pull/64

**Comment by cscorley** [comment]
We should be able to avoid platform specific hashing issues by supplying our own hasher to the plugin now via the `.checksum_resource::<PhysicsRollbackState>(HASHER)` option.  Very exciting!  But would want to confirm this is the case first.
