### ISSUE TITLE
Game freezes every 5-10 seconds

### ISSUE THREAD

**Issue by JulianGodd** [cscorley/bevy_ggrs_rapier_example#34]
When running the demo with two instances on the same machine, the demo freezes for around a second every 5-10 seconds. It doesn't seem to be affected by user input. I tested on both windows and linux. Switching to building release yields the same result.

Sorry if I'm missing something and this is an intentional debugging tool.

Thanks for paving the way in this sparsely traveled feature

**Comment by cscorley** [comment]
There is actually a intentional pause implemented which executes every 10 seconds.  https://github.com/cscorley/bevy_ggrs_rapier_example/blob/main/src/physics.rs#L63

This exists because I ran into this being a desync issue before!

**Comment by JulianGodd** [comment]
Sorry about that, thanks for the help!

**Comment by cscorley** [comment]
No problem, my apologies for missing this issue for so long :)
